# Generated by Django 5.1.6 on 2025-03-28 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_scheduledpost_profile_is_social_media_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title', max_length=255)),
                ('description', models.TextField(help_text='Detailed campaign description')),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='Target funding amount in dollars', max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, help_text='Total funds raised so far', max_digits=10)),
                ('itemized_budget', models.JSONField(blank=True, help_text='Optional JSON field for itemized budget breakdown', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional video pitch URL for the campaign', null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional campaign image', null=True, upload_to='campaign_images/')),
                ('approved', models.BooleanField(default=False, help_text='Indicates whether the campaign is approved by moderators')),
                ('live', models.BooleanField(default=False, help_text='Indicates whether the campaign is live and accepting donations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who created the campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
