# Generated by Django 5.1.6 on 2025-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crowdfunding Campaign', 'verbose_name_plural': 'Crowdfunding Campaigns'},
        ),
    ]
